name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt install -y g++ gcc g++-multilib gcc-multilib
    - name: make
      run: make
      working-directory: src/dlls
